### ISSUE TITLE
when trying to login for the first time

### ISSUE THREAD

**Issue by AlankruthaChandra** [iprhub/iprhub-project-portal#17]
I saved the PWD in the browser before logging in for the first time, when trying to login for the first time, the login button is deactivated until I click on the email/pwd tab.

**Comment by chaitanyareddyk** [comment]
Because of inconsistencies of web browsers, you can't rely that the change event will be triggered when browser autocompletes an input field. There is a simple workaround to use the setInterval() function that will monitor for changes at regular intervals. Since we are dealing with small form with only a couple of input fields it can be used safely without noticeable lags.
reference: [here](https://stackoverflow.com/questions/24057284/enable-button-when-browser-fills-data-automatically)
